trigger:
- master

variables:
  #WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_3_FULL.zip'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_FULL.zip'
jobs:
- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraMediaSource'
    workingDirectory: 'AgoraMediaSource/'
    scheme: 'AgoraMediaSource/'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraMediaSource.sln'
    sdkVersion: '3_0_0'
    sdkFolderVersion: '3.0.0'
    Machine: x86
#Windows Demo
- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraAudioIO'
    workingDirectory: 'AgoraAudioIO-Windows'
    scheme: 'Agora-String-Account-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraExternalCapture.sln'
    sdkVersion: '3_0_0'
    sdkFolderVersion: '3.0.0'
    Machine: x86