trigger:
- master

variables:
  #WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_3_FULL.zip'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_FULL.zip'
jobs:
- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraMediaSourceWindows'
    workingDirectory: 'Windows/'
    scheme: 'Windows/'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraMediaSource.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'
#Windows Demo
- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraAudioIOWindows'
    workingDirectory: 'AgoraAudioIO-Windows'
    scheme: 'Agora-String-Account-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraExternalCapture.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'